# Generated by Django 4.2.6 on 2023-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
